name: Lambda Deployment
on: 
  push:
    branches:
      - main
    paths:
      - 'lambda_function/hello_earth/**'
jobs:
  hello_earth_deployment:
    runs-on: self-hosted
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Deploy hello_earth
          if: contains(github.event.head_commit.modified, 'lambda_function/hello_earth')
          run: |
            cd lambda_function/hello_earth
            zip -r hello_earth.zip ./*
            aws s3 cp hello_earth.zip s3://bted-lambda-deploy-cicd/hello_earth.zip
            aws lambda update-function-code --function-name demo2 --s3-bucket bted-lambda-deploy-cicd --s3-key hello_earth.zip