name: Lambda Deployment

on: 
  push:
    branches:
      - master
      - main
    paths:
      - 'lambda_function/hello_world/**'
jobs:
  hello_world_deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy hello_world
        run: |
          cd lambda_function/hello_world
          zip -r hello_world.zip ./*
          aws s3 cp hello_world.zip s3://bted-lambda-deploy-cicd/hello_world.zip
          aws lambda update-function-code --function-name demo --s3-bucket bted-lambda-deploy-cicd --s3-key hello_world.zip